pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh '''
                cd Day-08-jenkins-docker-ci
                docker build -t day08-jenkins-app .
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop day08-ci || true
                docker rm day08-ci || true
                docker run -d --network host --name day08-ci day08-jenkins-app
                '''
            }
        }
    }
}

