pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Day-15-devops-capstone') {
                    echo 'Building Docker Image...'
                    sh 'docker build -t day15-capstone .'
                }
            }
        }

        stage('Deploy Application') {
            steps {
                dir('Day-15-devops-capstone') {
                    echo 'Deploying Application...'
                    sh './scripts/deploy.sh'
                }
            }
        }

        stage('Health Check') {
            steps {
                dir('Day-15-devops-capstone') {
                    echo 'Running Health Check...'
                    sh './scripts/health-check.sh'
                }
            }
        }

    }

    post {

        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }

    }

}